<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-3N7FDE7" failures="1" tests="12" name="testcases.SignInTest" time="3.862" errors="0" timestamp="2025-02-03T14:58:06 IST" skipped="0">
  <testcase classname="testcases.SignInTest" name="ValidateUrl" time="0.341"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="IsLogoDisplayed" time="0.106"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="IsWelcomeDisplayed" time="0.120"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="IsrememberDisplayed" time="0.112"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="SignInDisplayed" time="0.065"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="rememberClick" time="0.204"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="IsForgot" time="0.345">
    <failure message="did not expect [https://erpindia.inscol.com/auth/sign-in] but found [https://erpindia.inscol.com/auth/sign-in]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect [https://erpindia.inscol.com/auth/sign-in] but found [https://erpindia.inscol.com/auth/sign-in]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failEquals(Assert.java:1041)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:147)
at org.testng.Assert.assertNotEquals(Assert.java:1531)
at org.testng.Assert.assertNotEquals(Assert.java:1535)
at testcases.SignInTest.IsForgot(SignInTest.java:74)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- IsForgot -->
  <system-out/>
  <testcase classname="testcases.SignInTest" name="enterusername" time="0.585"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="passwordToggleTest" time="0.776"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="enterpassword" time="0.325"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="register" time="0.349"/>
  <system-out/>
  <testcase classname="testcases.SignInTest" name="IsSignClicked" time="0.534"/>
  <system-out/>
</testsuite> <!-- testcases.SignInTest -->
